project:
  type: website

website:
  google-analytics: "G-LY03001X9Q"
  cookie-consent: true
  title: "blog.ashwinramesh.co.in"
  site-url: https://blog.ashwinramesh.co.in/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ashwinr64
      - icon: twitter
        href: https://twitter.com/ashwinr64
format:
  html:
    theme: cosmo
    css: styles.css

resources:
  - CNAME
